name: Production Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Prod Release
        run: |
          # We pass the version code calculation to keep it in sync with your logic
          ./gradlew assembleProdRelease \
          -PnewVersionCode=$((558 + ${{ github.run_number }}))

      - name: Sign APK
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/prod/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 36.1.0

      - name: Rename APK
        id: rename
        run: |
          # Use github.ref_name to get the tag directly (e.g., 5.4.21)
          VERSION="${{ github.ref_name }}"
          NEW_NAME="ActivityManager-${VERSION}.apk"

          mv "${{ steps.sign_app.outputs.signedFile }}" "$NEW_NAME"
          echo "path=$NEW_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.rename.outputs.path }}
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
